#!/usr/bin/env python3
import os
import sys
import tomlkit
import json

try:
    in_filename = sys.argv[1]
except IndexError:
    print("Missing filename argument")
    sys.exit(1)

in_name, in_ext = os.path.splitext(in_filename)
out_filename = f"{in_name}.json"

with open(in_filename, "rt") as f:
    d = tomlkit.load(f)

json = json.dumps(d, indent=4)

with open(out_filename, "wt") as f:
    f.write(json)


